### What is an outlier?
An outlier is a data point in a data set that is distant from all other observations. A data point that lies outside the overall distribution of the dataset.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### What are the criteria to identify an outlier?

1. Data point that falls outside of 1.5 times of an interquartile range above the 3rd quartile and below the 1st quartile
2. Data point that falls outside of 3 standard deviations. we can use a z score and if the z score falls outside of 3 standard deviation are outliers

### What is the reason for an outlier to exists in a dataset?

1. Variability in the data
2. An experimental measurement error

### What are the impacts of having outliers in a dataset?

1. It causes various problems during our statistical analysis
2. It may cause a significant impact on the mean and the standard deviation

### Various ways of finding the outlier.
1. Using scatter plots
2. Box plot
3. using z score
4. using the IQR interquantile range



In [11]:
dataset= [11,10,12,14,12,15,14,13,15,102,12,14,17,19,107, 10,13,12,14,12,108,12,11,14,13,15,10,15,12,10,14,13,15,10]

# Here[102, 107, 108] are outlier

## 1. Detecting outlier using Z score

### Using Z score

Formula for Z score = (Observation — Mean)/Standard Deviation

z = (X — μ) / σ

In [19]:
outliers=[]
z_value=[]
def detect_outliers(data):
    
# This is  3rd STD threshold  
    threshold=3
    
    mean = np.mean(data)
    std =np.std(data)
    
    
    for i in data:
        z_score= (i - mean)/std 
        z_value.append(z_score)
        #print(z_score)
        # This Z value <-3 or >3 are outlier, so taken abs(z_score)
        if np.abs(z_score) > threshold:
            outliers.append(i)
    return outliers

In [20]:
outlier_pt=detect_outliers(dataset)

In [22]:
outlier_pt

[102, 107, 108]

> Here [102, 107, 108] are outlier which has z value

In [28]:
z_value[:10]


[-0.38587723217963826,
 -0.4237958041279264,
 -0.3479586602313501,
 -0.27212151633477377,
 -0.3479586602313501,
 -0.23420294438648565,
 -0.27212151633477377,
 -0.31004008828306195,
 -0.23420294438648565,
 3.064712815114584]

# 2. InterQuantile Range

75%- 25% values in a dataset

### Steps
#### 1. Arrange the data in increasing order
#### 2. Calculate first(q1) and third quartile(q3)
#### 3. Find interquartile range (q3-q1)
#### 4.Find lower bound q1*1.5
#### 5.Find upper bound q3*1.5

Anything that lies outside of lower and upper bound is an outlier

In [29]:
## Perform all the steps of IQR
sorted(dataset)

[10,
 10,
 10,
 10,
 10,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 15,
 15,
 15,
 17,
 19,
 102,
 107,
 108]

In [30]:
quantile1, quantile3= np.percentile(dataset,[25,75])

In [31]:
print(quantile1,quantile3)

12.0 15.0


In [32]:
## Find the IQR

iqr_value=quantile3-quantile1
print(iqr_value)

3.0


In [34]:
## Find the lower bound value and the higher bound value

lower_bound_val = quantile1 -(1.5 * iqr_value) 
upper_bound_val = quantile3 +(1.5 * iqr_value) 

In [20]:
print(lower_bound_val,upper_bound_val)

7.5 19.5


In [38]:
outlier_IQR = []
for i in dataset:
    if i < lower_bound_val or i > upper_bound_val :
        outlier_IQR.append(i)
        

In [39]:
outlier_IQR

[102, 107, 108]

> Here [102, 107, 108] are outlier which from IQR method